"""Rotating-block CV + permutation Monte Carlo + sealed-holdout evaluation.

Usage: python scripts/tourney_validate.py <dt_dir> <grid_dir>

Consumes the per-config per-day P&L matrix produced by tourney_run.py. Everything
here is matrix work, which is why the Monte Carlo is affordable: a config's entry
SELECTION never depends on outcomes, so the null is generated by re-scoring fixed
selections under shuffled market outcomes.
"""
import json
import os
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(__file__))
import tourney_engine as T
from tourney_run import DEPLOY, grid_for, K_BLOCKS, N_PERM


def block_split(days, k):
    return [list(x) for x in np.array_split(np.array(days), k)]


def cv_select(M, dev_days, k=K_BLOCKS, min_pos_blocks=4):
    """Rotating-block CV. Returns (per-fold held-out score of the selected config,
    the config chosen each fold, and the mean IS score of those winners)."""
    bl = block_split(dev_days, k)
    out = []
    for f in range(k):
        te = bl[f]
        tr = [d for j, b in enumerate(bl) if j != f for d in b]
        tr_cols = [f"d_{x}" for x in tr if f"d_{x}" in M.columns]
        te_cols = [f"d_{x}" for x in te if f"d_{x}" in M.columns]
        if not tr_cols or not te_cols:
            continue
        is_mean = M[tr_cols].mean(axis=1)
        # robustness constraint: positive in >=4 of the 5 IS blocks
        blk_means = []
        for j, b in enumerate(bl):
            if j == f:
                continue
            cc = [f"d_{x}" for x in b if f"d_{x}" in M.columns]
            if cc:
                blk_means.append(M[cc].mean(axis=1))
        pos_blocks = (pd.concat(blk_means, axis=1) > 0).sum(axis=1)
        eligible = is_mean[pos_blocks >= min(min_pos_blocks, len(blk_means))]
        if eligible.empty:
            eligible = is_mean
        win = eligible.idxmax()
        out.append(dict(fold=f, winner=int(win), is_mean=float(is_mean[win]),
                        oos_mean=float(M.loc[win, te_cols].mean())))
    return pd.DataFrame(out)


def permute_outcomes(d, rng):
    """Shuffle market-level outcomes within (day, interval, asset). Destroys the
    feature->outcome link while preserving volume, structure and outcome balance."""
    key = d.day + "|" + d.interval + "|" + d.asset
    move = d.groupby([key, d.epoch]).move_bps.first().reset_index()
    move.columns = ["grp", "epoch", "move"]
    newmove = move.copy()
    for g, sub in move.groupby("grp"):
        newmove.loc[sub.index, "move"] = rng.permutation(sub["move"].to_numpy())
    mp = dict(zip(zip(newmove.grp, newmove.epoch), newmove.move))
    nm = np.array([mp[(k, e)] for k, e in zip(key.to_numpy(), d.epoch.to_numpy())])
    return ((nm >= 0) == (d.side.to_numpy() == "Up")).astype(float)


def main(dt_dir, grid_dir):
    d, stops = T.load(dt_dir)
    split = json.load(open(os.path.join(grid_dir, "split.json")))
    dev_days, hold_days = split["dev"], split["holdout"]
    rng = np.random.default_rng(20260727)
    report = {}

    for iv in ("5m", "15m"):
        gp = os.path.join(grid_dir, f"grid_{iv}.parquet")
        if not os.path.exists(gp):
            continue
        M = pd.read_parquet(gp)
        cfgs = grid_for(iv)
        daycols_dev = [f"d_{x}" for x in dev_days if f"d_{x}" in M.columns]
        daycols_hold = [f"d_{x}" for x in hold_days if f"d_{x}" in M.columns]
        dep_i = int(M.index[M.tag == "DEPLOYED"][0])

        print(f"\n{'='*78}\n{iv}: {len(M)} configs | dev {len(daycols_dev)}d | "
              f"sealed holdout {len(daycols_hold)}d\n{'='*78}")
        cv = cv_select(M, dev_days)
        dep_oos = []
        for f, te in enumerate(block_split(dev_days, K_BLOCKS)):
            cc = [f"d_{x}" for x in te if f"d_{x}" in M.columns]
            if cc:
                dep_oos.append(M.loc[dep_i, cc].mean())
        print("\n-- rotating-block CV (selection procedure, not a hand-picked config) --")
        print(cv.to_string(index=False))
        proc = cv.oos_mean.mean()
        depm = float(np.mean(dep_oos))
        print(f"\n  procedure mean OOS $/day = {proc:+.3f}")
        print(f"  DEPLOYED  mean OOS $/day = {depm:+.3f}")
        print(f"  edge over deployed       = {proc-depm:+.3f}")
        print(f"  overfitting tax (IS-OOS) = {cv.is_mean.mean()-proc:+.3f}")

        # ---- permutation null for the whole selection procedure ----
        print(f"\n-- permutation Monte Carlo ({N_PERM} shuffles) --", flush=True)
        sel_cache = {i: T.select(d, cfgs[i][0]) for i in M.index}
        nulls = []
        for p in range(N_PERM):
            wperm = permute_outcomes(d, rng)
            cols = {}
            for i in M.index:
                pos = sel_cache[i]
                s = T.score(d, pos, stops, delayed=True, exit_mode="band",
                            won_override=wperm[pos] if len(pos) else None)
                cols[i] = (s.groupby("day").pnl.sum() if len(s) else pd.Series(dtype=float))
            Mn = pd.DataFrame({f"d_{k}": v for k, v in
                               pd.DataFrame(cols).T.items()}).fillna(0.0)
            Mn["tag"] = M.tag.values
            cvn = cv_select(Mn, dev_days)
            nulls.append(cvn.oos_mean.mean())
            if (p + 1) % 25 == 0:
                print(f"   perm {p+1}/{N_PERM}", flush=True)
        nulls = np.array(nulls)
        pval = float((nulls >= proc).mean())
        print(f"  null mean {nulls.mean():+.3f}, p95 {np.percentile(nulls,95):+.3f}, "
              f"max {nulls.max():+.3f}")
        print(f"  observed {proc:+.3f} -> permutation p = {pval:.4f}")

        # ---- final: select on ALL dev days, evaluate ONCE on the sealed holdout ----
        is_all = M[daycols_dev].mean(axis=1)
        bl = block_split(dev_days, K_BLOCKS)
        blkm = pd.concat([M[[f"d_{x}" for x in b if f"d_{x}" in M.columns]].mean(axis=1)
                          for b in bl], axis=1)
        elig = is_all[(blkm > 0).sum(axis=1) >= 4]
        final_i = int((elig if not elig.empty else is_all).idxmax())
        print(f"\n-- SEALED HOLDOUT (one evaluation) --")
        print(f"  selected config #{final_i} tag={M.loc[final_i,'tag']}")
        print(f"  cfg = {cfgs[final_i][0]}")
        print(f"  dev  $/day  selected {is_all[final_i]:+.3f} | deployed {is_all[dep_i]:+.3f}")
        hs = float(M.loc[final_i, daycols_hold].mean())
        hd = float(M.loc[dep_i, daycols_hold].mean())
        print(f"  HOLDOUT $/day selected {hs:+.3f} | deployed {hd:+.3f} | diff {hs-hd:+.3f}")
        report[iv] = dict(proc_oos=proc, deployed_oos=depm, pval=pval,
                          holdout_sel=hs, holdout_dep=hd, final_cfg=cfgs[final_i][0],
                          final_tag=M.loc[final_i, "tag"])
    with open(os.path.join(grid_dir, "report.json"), "w") as fh:
        json.dump(report, fh, indent=1, default=str)
    return report


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
